apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming-service-filesystem-deployment
spec:
  replicas: 3 # More file storage and retrivel
  selector:
    matchLabels:
      app: filesystem-service
      service: filesystem
  template:
    metadata:
      labels:
        app: filesystem-service
        service: filesystem
    spec:
      containers:
      - name: filesystem
        image: harkarank/project2:filesystem  # Updated image reference with tag
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: uploaded-videos
          mountPath: /app/files
      volumes:
        - name: uploaded-videos
          persistentVolumeClaim:
            claimName: uploaded-videos-pvc
