version: '3.3'

services:
  auth:
    build: ./auth
    networks:
      - app-network
    depends_on:
      - "enter-web-app"
      - "result-web-app"
  
  enter-web-app:
    build: ./enter-web-app
    restart: always
    hostname: enter-web-app
    networks:
      - app-network
    depends_on:
      - "mysql-db"
  
  result-web-app:
    build: ./result-web-app
    networks:
      - app-network

  analytics:
    build: ./analytics
    restart: always
    hostname: analytics
    networks:
      - app-network
    depends_on:
      - "mysql-db"
      - "mongo-db"

  mysql-db:
    build: ./mysqlDB
    hostname: mysqlDB
    networks:
      - app-network

  mongo-db:
    build: ./mongoDB
    hostname: mongoDB
    networks:
      - app-network

networks:
  app-network:
    name: app-network

