version: '3.3'

services:
  auth:
    build: ./auth
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - "enter-web-app"
      - "result-web-app"
  
  enter-web-app:
    build: ./enter-web-app
    restart: always
    ports:
     - "8080:8080"
    hostname: enter-web-app
    networks:
      - app-network
    depends_on:
      - "mysql-db"
  
  result-web-app:
    build: ./result-web-app
    ports:
     - "8090:8090"
    networks:
      - app-network

  analytics:
    build: ./analytics
    restart: always
    ports:
     - "8100:8100"
    hostname: analytics
    networks:
      - app-network
    depends_on:
      - "mysql-db"
      - "mongo-db"

  mysql-db:
    build: ./mysqlDB
    ports:
     - "3307:3306"
    hostname: mysqlDB
    networks:
      - app-network

  mongo-db:
    build: ./mongoDB
    ports:
     - "2717:27017"
    hostname: mongoDB
    networks:
      - app-network

networks:
  app-network:
    name: app-network

