version: '3'
services:

  authentication:
    networks:
      - mynetwork
    build:
      context: ./authentication
    ports:
      - "5001:5001"
    # other configurations...

  filesystem:
    networks:
      - mynetwork
    build:
      context: ./filesystem
    ports:
      - "5003:5003"
    volumes:
      - uploaded_videos:/app/files
    # other configurations...

  upload:
    networks:
      - mynetwork
    build:
      context: ./upload
    ports:
      - "5002:5002"

  video_stream:
    networks:
      - mynetwork
    build:
      context: ./video_stream
    ports:
      - "5000:5000"
    volumes:
      - uploaded_videos:/app/files

  mysql:
    image: mysql:latest
    build:
      context: ./mysql
    ports:
    - "3307:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=vid
      - MYSQL_DATABASE=videos
      # - MYSQL_ROOT_PASSWORD=vid
      # - DB_USERNAME=root
      # - DB_PASSWORD=vid
      # - DB_HOST=host.docker.internal
      # # - DB_PORT=3306
      # - DB_NAME=videos
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
  uploaded_videos: