apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-streaming-service-upload-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-streaming-service-upload-deployment
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60


# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: video-streaming-service-upload-deployment-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: video-streaming-service-upload-deployment
#   minReplicas: 2
#   maxReplicas: 6
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 60
