version: '3'

services:
  enter_data:
    build: ./enter_data
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
      - auth_service

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"

  show_results:
    build: ./show_results
    ports:
      - "8002:8002"
    depends_on:
      - mongo_db
      - auth_service

  analytics_service:
    build: ./analytics_service
    depends_on:
      - mysql_db
      - mongo_db

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'dataDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-data:/var/lib/mysql

  mongo_db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data:
