apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming-service-upload-deployment
spec:
  replicas: 2 # Distributes load during increased user activity ( Different upload sizes and processing times)
  selector:
    matchLabels:
      app: upload-service
      service: upload
  template:
    metadata:
      labels:
        app: upload-service
        service: upload
    spec:
      containers:
      - name: upload
        image: harkarank/project2:upload-new  # Updated image reference with tag
        ports:
        - containerPort: 5002

