CREATE DATABASE IF NOT EXISTS video;
USE video;

CREATE TABLE IF NOT EXISTS Video (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100),
    path VARCHAR(200)
);

DROP USER IF EXISTS 'vid'@'%';
CREATE USER 'vid'@'%' IDENTIFIED BY 'vid';
GRANT ALL PRIVILEGES ON video.* TO 'vid'@'%';
FLUSH PRIVILEGES;
