apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploaded-videos-pv
spec:
  storageClassName: manual  # Define your storage class if needed
  capacity:
    storage: 10Gi  # Define your desired storage size
  accessModes:
    - ReadWriteMany  # Ensure multiple pods can read and write to this volume
  hostPath:
    path: "/mnt/data/uploaded-videos"  # Define the path to your shared storage
