apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming-service-authentication-deployment
spec:
  replicas: 2 # Only 2 users have access so not really needed too much
  selector:
    matchLabels:
      app: authentication-service
      service: authentication
  template:
    metadata:
      labels:
        app: authentication-service
        service: authentication
    spec:
      containers:
      - name: authentication
        image: harkarank/project2:auth-new
        ports:
        - containerPort: 5001

